name: Swift

on: 
  push:
    branches:
      - develop

jobs:
  build:

    runs-on: macOS-latest
    
    steps:
    - uses: actions/checkout@master
    - name: Start xcodebuild test
      run: xcodebuild clean test -project MusicTouch.xcodeproj -scheme MusicTouch -destination "platform=iOS Simulator,name=iPhone 11 Pro"

